allowBuilds:
  unrs-resolver: true
engineStrict: true
minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  - '@taiyme/*'
  # Renovate security update: pnpm@11.5.3 || 11.8.0
  - pnpm@11.5.3 || 11.8.0
publicHoistPattern:
  - '@typescript/*'
saveExact: true
shellEmulator: true
trustPolicy: no-downgrade
