name: Deploy to GitHub Pages

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: Enable corepack
        run: |
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm dlx @eslint/config-inspector build --config=./eslint.config.inspector.js --files=false

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/.eslint-config-inspector

  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    needs:
      - build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
