name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.event.pull_request.head.repo.full_name || github.repository }}-
    ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    env:
      cache-path: ${{ github.workspace }}/node_modules/.cache/eslint
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Create cache key
        id: cache-keys
        env:
          lockfile_hash: ${{ hashFiles('**/pnpm-lock.yaml') }}
        run: |
          cache_name="eslint"
          cache_platform="${RUNNER_OS}-${RUNNER_ARCH}-${lockfile_hash}"
          cache_primary_key="${cache_name}-${cache_platform}-${GITHUB_SHA}"
          cache_restore_key="${cache_name}-${cache_platform}-"
          echo "primary=${cache_primary_key}" >> "$GITHUB_OUTPUT"
          echo "restore=${cache_restore_key}" >> "$GITHUB_OUTPUT"

      - name: Cache ESLint
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ${{ env.cache-path }}
          key: ${{ steps.cache-keys.outputs.primary }}
          restore-keys: ${{ steps.cache-keys.outputs.restore }}

      - name: Run ESLint
        env:
          cache_location: ${{ env.cache-path }}
        run: |
          pnpm exec eslint \
            --cache \
            --cache-location "$cache_location" \
            --cache-strategy content
